#ifndef __PROTOCOL_H__
#define __PROTOCOL_H__


enum msg_type_command
{
	MSG_COMMAND_STATUS,
	MSG_COMMAND_PING,
	MSG_COMMAND_RESET,
	MSG_COMMAND_RELAIS,
	MSG_COMMAND_EEPROM_SET,
	MSG_COMMAND_EEPROM_GET
};

enum msg_type_eeprom
{
	MSG_EEPROM_ID,
	MSG_EEPROM_RELAIS1,
	MSG_EEPROM_RELAIS2,
	MSG_EEPROM_RELAIS3,
	MSG_EEPROM_RELAIS4,
	MSG_EEPROM_RELAIS5,
	MSG_EEPROM_RELAIS6
};

enum msg_type_status
{
	MSG_STATUS_POWERUP,
	MSG_STATUS_RELAIS,
	MSG_STATUS_UPTIME,
	MSG_STATUS_EEPROM_RELAIS1,
	MSG_STATUS_EEPROM_RELAIS2,
	MSG_STATUS_EEPROM_RELAIS3,
	MSG_STATUS_EEPROM_RELAIS4,
	MSG_STATUS_EEPROM_RELAIS5,
	MSG_STATUS_EEPROM_RELAIS6,

	MSG_STATUS_HR20_TEMPIS,
	MSG_STATUS_HR20_TEMPSET,
	MSG_STATUS_HR20_VALVE,
	MSG_STATUS_HR20_VOLTAGE,
	MSG_STATUS_HR20_MODE,
	MSG_STATUS_HR20_AUTO_TEMPERATURE,
	MSG_STATUS_HR20_EEPROM
};

#define MSG_ID_MASTER_SLAVE 0x0F0

#endif
